# Generated by Django 2.1 on 2019-05-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Plan', verbose_name='plan_ticket')),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_status',
        ),
    ]
