# Generated by Django 2.1 on 2019-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190529_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_cinema',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_column',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
