# Generated by Django 2.1 on 2019-05-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190529_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tickets',
            new_name='ticket_plan',
        ),
    ]
