# Generated by Django 2.1 on 2019-05-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20190529_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_cinema',
        ),
    ]
