# Generated by Django 2.1 on 2019-06-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_remove_ticket_ticket_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='cinema_movie',
        ),
    ]
