# Generated by Django 2.1 on 2019-06-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_remove_cinema_cinema_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
